server:
  port: 8082

spring:
  application:
    name: TransportationService
  datasource:
    url: jdbc:postgresql://localhost:5432/jpatest
    username: sa
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#https://runebook.dev/ru/docs/spring_boot/actuator
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always