server:
  port: 8082

spring:
  application:
    name: TransportationService
  datasource:
    url: jdbc:postgresql://localhost:5432/jpatest
    username: sa
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
